### ISSUE TITLE
How to set up video streaming service with Grapql?

### ISSUE THREAD

**Issue by jeffreyt02** [rgraphql/rgraphql#2]
I can't seem to find a good example on, how to create a video streaming service with grapql.  Cant seem 2 find  code on this matter.

**Comment by dmitry** [comment]
@jeffreyt02 it's not possible, because video streaming is not related to the structure, it's a streaming, not a structured JSON. It's the same as you would do the video streaming via REST - it's not possible, at least in normal world.

**Comment by jeffreyt02** [comment]
Thanks for responding,

I know you need to set a URL in a database to refer to the video you want to stream, but is that it? no error handeling,piping, or you dont have to make chunks? i wanna know, cant seem to find any repositories with any code on the matter

**Comment by paralin** [comment]
@jeffreyt02 You would have to set up something like HTTP Live Streaming, where each chunk is exposed as an array element, and the player is just grabbing the next chunk all the time.
